### PR TITLE
Fix pod keeps retrying `pull image`

### LINKED ISSUE #1226: Install drivers-one-shot keeps retrying `pull image`, > x10 slower than manually `docker pull`
When install `drivers-one-shot`, kuberenetes keeps retrying `pull image`.

It takes obviously long (>10x) than manually `docker pull the_image`.

> Failed to pull image "10.0.1.5:5000/openpai/drivers:yife-check_resource-12782c6-8": rpc error: code = Canceled desc = context canceled

image

### PR DESCRIPTION
**Pull request by hao1939**
fixes #1226

### CODE REVIEW

File: pai-management/k8sPaiLibrary/template/kubelet.sh.template [hunk 1]
```diff
@@ -48,4 +48,5 @@ docker run \
   --logtostderr=true \
   --pod-infra-container-image {{ clusterconfig['dockerregistry'] }}/pause-amd64:3.0 \
   --eviction-hard="memory.available<5%,nodefs.available<5%,imagefs.available<5%,nodefs.inodesFree<5%,imagefs.inodesFree<5%" \
+  --image-pull-progress-deadline=6m \
```
Comment (ydye) [inline pai-management/k8sPaiLibrary/template/kubelet.sh.template]: 6m is enough? Maybe, this time should be longer?

Comment (hao1939) [reply pai-management/k8sPaiLibrary/template/kubelet.sh.template]: It's enough for now.
We may add an configuration entry later, maybe in another PR.

Comment (ydye) [reply pai-management/k8sPaiLibrary/template/kubelet.sh.template]: Let's set it 10 min?

Comment (hao1939) [reply pai-management/k8sPaiLibrary/template/kubelet.sh.template]: Cool, I will update.

Comment (YitongFeng) [reply pai-management/k8sPaiLibrary/template/kubelet.sh.template]: If no pulling progress is made before this deadline, the image pulling will be cancelled. What will happen if the pulling canceled?

Comment (hao1939) [reply pai-management/k8sPaiLibrary/template/kubelet.sh.template]: @YitongFeng , it will retry.
If lucky, next retry may succeed, or it won't success forever.
