### PR TITLE
fix two bugs: add validation when submitting job by json #2375, Job List-filter UI fix #2479

### LINKED ISSUE #2479: Job List-filter UI fix
**Short summary about the issue/question**: 
1.The background color of Filter button should be transparent ;
2.There should be a frame (#ECECEC) under opened filter area.

Screenshot
image
Ref
image

### PR DESCRIPTION
**Pull request by yxwithu**
bug issue: https://github.com/Microsoft/pai/issues/2375

### CODE REVIEW

File: src/webportal/src/app/job/job-submit/job-submit.component.js [hunk 1]
```diff
@@ -60,7 +60,8 @@ const isValidJson = (str) => {
     valid = false;
   }
   if (!valid) {
-    alert('Please upload a valid json file: ' + errors);
+    // alert('Please upload a valid json file: ' + errors);
```
Comment (abuccts) [inline src/webportal/src/app/job/job-submit/job-submit.component.js]: remove the old line

File: src/webportal/src/app/job/job-submit/job-submit.component.js [hunk 2]
```diff
@@ -144,6 +145,23 @@ $(document).ready(() => {
...
 
+    // choose the first edit json box
+    $('[title="Edit JSON"]').filter(':first').one('click', () => {
+      // disable old save button to avoid saving automatically
+      let oldSave = $('[title="Edit JSON"]').filter(':first').next('div').children('[title=Save]')[0];
+      let newSave = oldSave.cloneNode(true);
+      oldSave.parentNode.replaceChild(newSave, oldSave);
+
+      // add new click listener
+      $(newSave).on('click', ()=>{
```
Comment (abuccts) [inline src/webportal/src/app/job/job-submit/job-submit.component.js]: add spaces around arrow

**Comment by Gerhut** [comment]
Hi @yxwithu

Please separate your fixes into 2 PRs
