### PR TITLE
[Rest Server] Add launched time for job

### LINKED ISSUE #3249: How to get the actual duration of the job，the appLaunchedTime have value while the job is still in waiting.
**Organization Name**: Advantech

**Short summary about the issue/question**: We want to calculate the actual duration time of a job, from the start of the job to the end of the job. We need to exclude the waiting time. At first we use the createdTime, and later we changed to use the appLaunchedTime. But when the job is still in waiting status, the appLaunchedTime appears. 

**Brief what process you are following**:

**How to reproduce it**:

**OpenPAI Environment**: Cluster
- OpenPAI version: 0.10.1
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Hardware (e.g. core number, memory size, storage size, GPU type etc.):
- Others:

**Anything else we need to know**:

### LINKED ISSUE #4295: Job API not return correct appLaunchedTime
Refer to https://github.com/microsoft/pai/blob/338f5a3e01c8c5fce9f81177d7de3cf154c304c9/src/rest-server/src/models/v2/job/k8s.js#L254

Currently `appLaunchedTime ` equal to `creationTimestamp`. So it will include waiting time. We need to return correct `appLaunchedTime`. And it's better to return `launchTime` for each task. Then we can monitor the actually resource utilization for job and task.

### PR DESCRIPTION
**Pull request by abuccts**
Add launched time for job.

Closes #4295.
Resolves #3249

### CODE REVIEW

File: src/rest-server/src/models/v2/job/k8s.js [hunk 1]
```diff
@@ -248,11 +249,11 @@ const convertFrameworkDetail = async (framework) => {
       retryDelayTime: framework.status.retryPolicyStatus.retryDelaySec,
       createdTime: new Date(framework.metadata.creationTimestamp).getTime(),
       completedTime: new Date(framework.status.completionTime).getTime(),
-      appId: framework.status.attemptStatus.instanceUID,
+      appId: attemptStatus.instanceUID,
       appProgress: completionStatus ? 1 : 0,
       appTrackingUrl: '',
-      appLaunchedTime: new Date(framework.metadata.creationTimestamp).getTime(),
-      appCompletedTime: new Date(framework.status.completionTime).getTime(),
+      appLaunchedTime: new Date(attemptStatus.runTime || attemptStatus.completionTime).getTime(),
```
Comment (yqwang-ms) [inline src/rest-server/src/models/v2/job/k8s.js]: Also update related doc for appLaunchedTime.

For a job attempt:
WholeDuration = CompletionTime - StartTime
RunningDuration = CompletionTime - LaunchedTime
WaitingDuration = WholeDuration - RunningDuration

For the whole job which may have multiple attempts:
WholeDuration = CompletionTime - StartTime
RunningTime = Sum_all_attempts (CompletionTime - LaunchedTime)
WaitingDuration = WholeDuration - RunningDuration

Comment (abuccts) [reply src/rest-server/src/models/v2/job/k8s.js]: added

**Comment by abuccts** [comment]
Test cases:

* submit a `sleep 1s` job, check whether `appLaunchedTime` equals to `appCompletedTime`
* submit a `sleep 10m` job, check whether `appLaunchedTime` equals to `appCompletedTime - 10m`
