### PR TITLE
Fix tensorboard precommand bug

### LINKED ISSUE #3796: tensorboard could not add precommand after toggle it
Repro steps:

1. In 16 bed, toggle the tensorboard option

image

2. open yaml editor and the tensorboard precommand is missing

image

3. compare with correct yaml:

image

### PR DESCRIPTION
**Pull request by debuggy**
In original code: 

```javascript  
if (!jobData.containData) {
    return;
}
```
If job data.containData is false,  the tensorboard command will not be prefixed.

closes #3796

### CODE REVIEW

File: src/webportal/src/app/job-submission/utils/utils.js [hunk 1]
```diff
@@ -183,6 +182,8 @@ function addTensorBoardCommandsToProtocolTaskRoles(protocol) {
 }
 
 export async function populateProtocolWithDataCli(user, protocol, jobData) {
```
Comment (Binyang2014) [inline src/webportal/src/app/job-submission/utils/utils.js]: Change this function name? It not only inject data cli into the command. It also used to inject the tensorflow cli.

Comment (debuggy) [reply src/webportal/src/app/job-submission/utils/utils.js]: done
