### PR TITLE
[Rest Server] Fix log path length

### LINKED ISSUE #4391: Cannot submit jobs with very long job name
How to reproduce:

1. Submit a job with a very long job name.

2. The job will keep in `WAITING` status.

3. `kubectl describe po` returns:

image

image

### PR DESCRIPTION
**Pull request by abuccts**
Fix log path length, set job name length limit to 255.

Closes #4391.

### CODE REVIEW

File: src/rest-server/src/models/v2/job/k8s.js [hunk 1]
```diff
@@ -636,6 +637,7 @@ const generateFrameworkDescription = (frameworkName, virtualCluster, config, raw
       labels: {
         userName: jobInfo.userName,
         virtualCluster: jobInfo.virtualCluster,
+        logPathInfix: jobInfo.logPathInfix,
```
Comment (Binyang2014) [inline src/rest-server/src/models/v2/job/k8s.js:640]: Can put this into annotations? Maybe we don't need to filter framework according to `logPathInfix`
