### PR TITLE
[Rest Server] Update virtual cluster metrics using scheduler api

### LINKED ISSUE #4332: Using `physicalCells` without `cellChildren` in hivedscheduler does not work in rest-server
How to reproduce:

In hivedscheduler configuration, if use `physicalCells` without `cellChildren` like: https://github.com/microsoft/hivedscheduler/blob/master/example/config/design/hivedscheduler.yaml#L147-L151 , rest-server will be unable to start.

### PR DESCRIPTION
**Pull request by abuccts**
Update virtual cluster resource metics using hived scheduler api.

Closes #4332.

### CODE REVIEW

File: src/rest-server/src/models/v2/virtual-cluster/k8s.js [hunk 1]
```diff
@@ -144,90 +147,90 @@ const getNodeResource = async () => {
...
+    // used, guaranteed, total resources
+    for (let vc of Object.keys(virtualCellCapacity)) {
+      if (vc in vcStatus) {
+        const cellQueue = [...vcStatus[vc]];
+        while (cellQueue.length > 0) {
+          const curr = cellQueue.shift();
+          if (curr.cellPriority === -1) {
+            continue;
+          }
+          if (curr.children) {
```
Comment (yqwang-ms) [inline src/rest-server/src/models/v2/virtual-cluster/k8s.js]: Fully trust hived result. Do not rewrite fields.
But this will depend on new version Hived, v0.3.1

**Comment by yqwang-ms** [comment]
>   style: PropTypes.object,

Have you also changed the VC usage to be like:
```
Used / (Total - Bad)
1 / (10 - 7) 
```
?

---
Refers to: src/webportal/src/app/home/home/virtual-cluster-statistics.jsx:229 in 41c43ea. [](commit_id = 41c43eaef2e657eaac6d6935ec4996af741fe80b, deletion_comment = False)

File: src/webportal/src/app/home/home/virtual-cluster-statistics.jsx [hunk 2]
```diff
@@ -101,8 +101,8 @@ const vcListColumns = [
     isResizable: true,
     onRender(vc) {
       const { resourcesUsed, resourcesTotal } = vc;
-      const resourceAvailable = vc.resourceAvailable || resourcesTotal;
-      const insufficient = !(resourceAvailable.GPUs === resourcesTotal.GPUs);
+      const resourcesGuaranteed = vc.resourcesGuaranteed || resourcesTotal;
```
Comment (yqwang-ms) [inline src/webportal/src/app/home/home/virtual-cluster-statistics.jsx]: >vc.resourcesGuaranteed || resourcesTotal; [](start = 34, length = 41)

In which case, the resourcesGuaranteed is null?

File: src/webportal/src/app/home/home/virtual-cluster-statistics.jsx [hunk 3]
```diff
@@ -101,8 +101,8 @@ const vcListColumns = [
...
+      const insufficient = !(resourcesGuaranteed.GPUs === resourcesTotal.GPUs);
```
Comment (yqwang-ms) [inline src/webportal/src/app/home/home/virtual-cluster-statistics.jsx]: Comment and expose resourcesGuaranteed is the (Total - Bad)

File: src/webportal/src/app/home/home/virtual-cluster-statistics.jsx (hunk 2 above)
Comment (abuccts) [reply src/webportal/src/app/home/home/virtual-cluster-statistics.jsx]: old version api

**Comment by yqwang-ms** [comment]
>   const virtualClusters = hivedObj.virtualClusters;

Seems you only need the hivedObj.physicalCluster.gpuTypes now.
So remove others, such as 
```
  const cellTypes = hivedObj.physicalCluster.cellTypes;
  const physicalCells = hivedObj.physicalCluster.physicalCells;
  const virtualClusters = hivedObj.virtualClusters;
```

---
Refers to: src/rest-server/src/config/vc.js:63 in 41c43ea. [](commit_id = 41c43eaef2e657eaac6d6935ec4996af741fe80b, deletion_comment = False)

File: src/webportal/src/app/home/home/virtual-cluster-statistics.jsx (hunk 3 above)
Comment (abuccts) [reply src/webportal/src/app/home/home/virtual-cluster-statistics.jsx]: changed to show "used / total - bad", no guaranteed.

File: src/webportal/src/app/home/home/virtual-cluster-statistics.jsx [hunk 4]
```diff
@@ -97,12 +98,12 @@ const vcListColumns = [
   {
     key: 'detail',
     minWidth: 200,
-    name: 'Detail',
+    name: 'Detail (Used / Total - Bad)',
```
Comment (yqwang-ms) [inline src/webportal/src/app/home/home/virtual-cluster-statistics.jsx]: >name: 'Detail (Used / Total - Bad)', [](start = 4, length = 36)

I mean:

name: 'Detail: Used / (Total - Bad)' ?

Comment (abuccts) [reply src/webportal/src/app/home/home/virtual-cluster-statistics.jsx]: what if there's no bad? seems there's no agreement on UI design yet

**Comment by yqwang-ms** [comment]
>   const virtualClusters = hivedObj.virtualClusters;

Just besteffort check the API, i.e. if API is down, just let the job able to submit

---
In reply to: [604857093](https://github.com/microsoft/pai/pull/4329#issuecomment-604857093) [](ancestors = 604857093)

---
Refers to: src/rest-server/src/config/vc.js:63 in 41c43ea. [](commit_id = 41c43eaef2e657eaac6d6935ec4996af741fe80b, deletion_comment = False)

File: src/webportal/src/app/home/home/virtual-cluster-statistics.jsx (hunk 4 above)
Comment (yqwang-ms) [reply src/webportal/src/app/home/home/virtual-cluster-statistics.jsx]: And always use  the format:
such as 1 / (10 - 0)

if u use insufficient, it will be:
1 / (10)

Which is inconsistent with the header.

---
In reply to: [399080739](https://github.com/microsoft/pai/pull/4329#discussion_r399080739) [](ancestors = 399080739)

**Comment by yqwang-ms** [comment]
>   return used / total;

rename to guaranteed?

---
Refers to: src/webportal/src/app/home/home/virtual-cluster-statistics.jsx:45 in bb08530. [](commit_id = bb08530cd7fc2a9c7cfaefae84e15b4f129baa95, deletion_comment = False)

File: src/webportal/src/app/home/home/virtual-cluster-statistics.jsx (hunk 4 above)
Comment (yqwang-ms) [reply src/webportal/src/app/home/home/virtual-cluster-statistics.jsx]: no bad = bad is 0

File: src/rest-server/src/models/v2/virtual-cluster/k8s.js (hunk 1 above)
Comment (abuccts) [reply src/rest-server/src/models/v2/virtual-cluster/k8s.js]: updated

**Comment by abuccts** [comment]
Test cases:

1. configure two gpu types, three virtual clusters with shared nodes in hived, check whether vc metrics are correct on webportal
2. preempt (shut down) several nodes, check whether guaranteed numbers are correct on webportal
